services:
  tech44mysql:
    container_name: tech44mysql
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: passtech44
      MYSQL_DATABASE: tech44
    ports:
      - "3306:3306"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - tech44_network
  tech44server:
    container_name: tech44server
    depends_on:
      - tech44mysql
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 8089:8089
    env_file:
      - ./server/.env
    networks:
      - tech44_network
  tech44app:
    container_name: tech44app
    depends_on:
      - tech44server
    build:
      context: ./apps
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

networks:
  tech44_network:
    driver: bridge

volumes:
  mysql-data:
